repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check .
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: python3 -m mypy pcc/ --strict-equality
        language: system
        always_run: true
        pass_filenames: false
      - id: pylint
        name: pylint
        entry: python3 -m pylint pcc/
        language: system
        types: [python]
        require_serial: true
        args: ["--rcfile=.pylintrc"]
